server:
  port: 8081
  servlet:
    contextPath: /transpLux
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/translux?user=root
    driverClassName: com.mysql.cj.jdbc.Driver