server:
  port: 8081
  servlet:
    contextPath: /transpLux
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/transplux?user=root
    driverClassName: com.mysql.cj.jdbc.Driver